# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: riceseed_counter
description: count number of seed using Ultralytics YOLO
version: 0.0.3
homepage: https://github.com/ultralytics/ultralytics_yolo.git

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  flutter: ">=3.19.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal plugin (local path)
  ultralytics_yolo:
    path: lib/ultralytics_yolo

  # Core functionality
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  camera: ^0.11.1
  camera_android: ^0.10.10
  image_picker: ^1.1.2
  photo_manager: ^3.6.4
  tflite_flutter: ^0.11.0
  image: ^3.0.1
  plugin_platform_interface: ^2.1.8
  sqflite: ^2.2.8+4
  provider: ^6.1.5
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ultralytics.ultralytics_yolo
        pluginClass: UltralyticsYoloPlugin
      ios:
        pluginClass: UltralyticsYoloPlugin

  uses-material-design: true

  assets:
    - assets/
